// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
// import "./globals.css";
// import Footer from "@/components/commom/footer";
// import Header from "@/components/commom/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const montserrat = Montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} ${inter.variable}
//         ${montserrat.variable}  h-full antialiased`}
//     >
//       <Header/>
//       <body className="min-h-full flex flex-col">{children}</body>
//         <Footer/>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { WishlistProvider } from "@/context/WishlistContext";
import { CartProvider } from "@/context/CartContext";
import FloatingWhatsappButton from "@/components/Whatsapp_Button/FloatingWhatsappButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
    ${geistSans.variable}
    ${geistMono.variable}
    ${inter.variable}
    ${montserrat.variable}
  `}
    >
      <body className="min-h-screen  font-[var(--font-montserrat)]">
        <CartProvider>
          <WishlistProvider>
            {children}
            <Toaster theme="dark" position="top-right" richColors />
            <FloatingWhatsappButton />
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
